### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ggcarlosr** [hispeedimagins/steem#1]
What a brother, given that you need a logo for the application, here is my proposal, what we had talked about in previous days in Discord.

![steemer-wall](https://user-images.githubusercontent.com/37964430/40254387-2fdc3ce4-5ab1-11e8-8b55-4b3dfb4bbe03.png)

**Comment by abdulmalikkhan655** [comment]
ggcarlosr is a scameer be carefull
