### ISSUE TITLE
App crashes during startup

### ISSUE THREAD

**Issue by djavalord** [hispeedimagins/steem#11]
### Expected behavior 
I expect the app to successfully start and run when ever I want to lunch it

### Actual behavior 
App crashed during startup
### How To reproduce 
* click on the app 
* give it some seconds to load
* the app will crash on the process 

Device : Tecno camon X. Android version 8. 1.0 Oreo 

### Recording of the bug
https://youtu.be/MWfCxg87YlI

**Comment by hispeedimagins** [comment]
Please tell me the app version you are using.

**Comment by hispeedimagins** [comment]
Also, please try uninstalling the app and also please make sure that you enter the correct
PRIVATE POSTING KEY.
Capitalised it so no other key is used hehe.
Please try this and let me know.
Thank you.

**Comment by djavalord** [comment]
* ### Logcats 
C:\platform-tools>adb devices
List of devices attached
0312511846003893        device


C:\platform-tools>adb logcat -d logcat.txt
--------- beginning of crash
07-17 09:48:00.193  4504  4504 E AndroidRuntime: FATAL EXCEPTION: main
07-17 09:48:00.193  4504  4504 E AndroidRuntime: Process: com.steemapp.lokisveil.steemapp, PID: 4504
07-17 09:48:00.193  4504  4504 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:438)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.createRequestDataClass(RequestsDatabase.kt:171)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.HelperQuestionsList(RequestsDatabase.kt:160)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.GetAllQuestions(RequestsDatabase.kt:81)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.DeleteOld(RequestsDatabase.kt:105)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment.addItems(FeedFragment.kt:528)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:433)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:51)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:83)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6524)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-17 09:48:00.193  4504  4504 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
07-17 20:48:25.332 22584 22584 E AndroidRuntime: FATAL EXCEPTION: main
07-17 20:48:25.332 22584 22584 E AndroidRuntime: Process: com.steemapp.lokisveil.steemapp, PID: 22584
07-17 20:48:25.332 22584 22584 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:438)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.createRequestDataClass(RequestsDatabase.kt:171)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.HelperQuestionsList(RequestsDatabase.kt:160)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.GetAllQuestions(RequestsDatabase.kt:81)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.DeleteOld(RequestsDatabase.kt:105)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment.addItems(FeedFragment.kt:528)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:433)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:51)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:83)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6524)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-17 20:48:25.332 22584 22584 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
07-17 21:02:45.768 22823 22823 E AndroidRuntime: FATAL EXCEPTION: main
07-17 21:02:45.768 22823 22823 E AndroidRuntime: Process: com.steemapp.lokisveil.steemapp, PID: 22823
07-17 21:02:45.768 22823 22823 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:438)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.createRequestDataClass(RequestsDatabase.kt:171)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.HelperQuestionsList(RequestsDatabase.kt:160)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.GetAllQuestions(RequestsDatabase.kt:81)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.DeleteOld(RequestsDatabase.kt:105)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment.addItems(FeedFragment.kt:528)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:433)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:51)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:83)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6524)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-17 21:02:45.768 22823 22823 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
07-17 23:27:19.024 13971 13971 E AndroidRuntime: FATAL EXCEPTION: main
07-17 23:27:19.024 13971 13971 E AndroidRuntime: Process: com.steemapp.lokisveil.steemapp, PID: 13971
07-17 23:27:19.024 13971 13971 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:438)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.createRequestDataClass(RequestsDatabase.kt:171)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.HelperQuestionsList(RequestsDatabase.kt:160)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.GetAllQuestions(RequestsDatabase.kt:81)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.DeleteOld(RequestsDatabase.kt:105)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment.addItems(FeedFragment.kt:528)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:433)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:51)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:83)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6524)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-17 23:27:19.024 13971 13971 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
07-17 23:30:47.647 14655 14655 E AndroidRuntime: FATAL EXCEPTION: main
07-17 23:30:47.647 14655 14655 E AndroidRuntime: Process: com.steemapp.lokisveil.steemapp, PID: 14655
07-17 23:30:47.647 14655 14655 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:438)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.createRequestDataClass(RequestsDatabase.kt:171)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.HelperQuestionsList(RequestsDatabase.kt:160)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.GetAllQuestions(RequestsDatabase.kt:81)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.DeleteOld(RequestsDatabase.kt:105)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment.addItems(FeedFragment.kt:528)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:433)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:51)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:83)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6524)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-17 23:30:47.647 14655 14655 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
07-17 23:34:19.897 15131 15131 E AndroidRuntime: FATAL EXCEPTION: main
07-17 23:34:19.897 15131 15131 E AndroidRuntime: Process: com.steemapp.lokisveil.steemapp, PID: 15131
07-17 23:34:19.897 15131 15131 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at android.database.CursorWindow.nativeGetString(Native Method)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at android.database.CursorWindow.getString(CursorWindow.java:438)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.createRequestDataClass(RequestsDatabase.kt:171)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.HelperQuestionsList(RequestsDatabase.kt:160)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.GetAllQuestions(RequestsDatabase.kt:81)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Databases.RequestsDatabase.DeleteOld(RequestsDatabase.kt:105)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment.addItems(FeedFragment.kt:528)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:433)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.steemapp.lokisveil.steemapp.Fragments.FeedFragment$GetFeed$s$1.onResponse(FeedFragment.kt:51)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:83)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6524)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-17 23:34:19.897 15131 15131 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by hispeedimagins** [comment]
Thank you for that. I had already got it by mail. hehe. Please update the app and check it if works now.
