### ISSUE TITLE
App crashes while uploading image

### ISSUE THREAD

**Issue by realrufans** [hispeedimagins/steem#12]
#### Expected behavior
It was expected for the app to successfully upload image while creating post.

#### Actual behavior
The app crashes while trying to upload image via gallery.

#### How to reproduce
* Launch the app then click on **message** icon to create post
* Locate the file upload icon on the top right to upload image from gallery.
* Select an image to upload

---
* Browser/App version: Steemer V 1.0.9.1
* Operating system: Android version 8. 1.0 Oreo Tecno camon X pro.

#### Recording Of The Bug
https://youtu.be/B319xLhIgWw

**Comment by shaphir** [comment]
Similar [#7](https://github.com/hispeedimagins/steem/issues/7)

**Comment by shaphir** [comment]
It's should be on the ```version 1.4.4``` not ```1.0.9.1```

**Comment by hispeedimagins** [comment]
please try updating the app and let me know if it works now.
