### ISSUE TITLE
Links aren't clickable from comment section

### ISSUE THREAD

**Issue by realrufans** [hispeedimagins/steem#18]
---

#### Expected behavior
Link ought to be clickable  in every section of the app.

---

#### Actual behavior
Links aren't  clickable from  **comment** window

---

#### How to reproduce
* login, locate a post to view it's comment. <Sup>( Look for post with link(s) in it's comment.)</Sup>
* click on **comments** at top right of the post window
* Look for a comment with a Link then try clicking on the link. 

---

* App version: Steemer V 1.4.4
* Operating system: Android version 8. 1.0 Oreo Tecno camon Xpro. 

#### Recording Of The Bug
https://youtu.be/1Yz1pRQQpjA

**Comment by hispeedimagins** [comment]
Yup, that has been stopped for now, because of a small issue while creating textviews. I plan to overhaul the whole mechanism so did not bother to re add it. I'll put it up in the next update.

**Comment by hispeedimagins** [comment]
fixed
