### ISSUE TITLE
Steemer automatically assign Omaumau as location to every user with an empty location.

### ISSUE THREAD

**Issue by realrufans** [hispeedimagins/steem#20]
---

#### Expected behavior
If a user's location is empty on Steemit.com , it's also expected to be empty on Steemer.

---

#### Actual behavior
Steemer automatically assign **Omaumau** as location to every user with an empty location.

---

#### How to reproduce
* Note at least two accounts with an empty location on Steemit.com <Sup>( ```readarthurss``` and ``` flauwy``` has an empty location.)</Sup>
* login with Steemer, then try checking the noted user's location on steemer  

---

* App version: Steemer V 1.4.4
* Operating system: Android version 8. 1.0 Oreo Tecno camon Xpro. 

#### Recording Of The Bug
https://youtu.be/MOJFuF2NSIQ

**Comment by hispeedimagins** [comment]
hahaah that is be design, Omaumau was an asteroid which passed Earth recently which had never before been seen, it was cigar shaped.

**Comment by realrufans** [comment]
Hahaha , okay I will check Google for more info 😄
