### ISSUE TITLE
Steemer V1.4.5 - Reward claiming Isn't Working

### ISSUE THREAD

**Issue by realrufans** [hispeedimagins/steem#23]
#### Project Information
* Repository:
https://github.com/hispeedimagins/steem
* Project Name: Steemer 
* Publisher :hispeedimagins

---

#### Expected behavior
Rewards should be successfully claimed.

---

#### Actual behavior
Reward aren't claiming, It keeps  popping up notification  to claim  same rewards  anytime the app is launched.

---

#### How to reproduce
**Make sure you have unclaimed reward**
* Launch Steemer then login 
* Click on okay after reward claiming notification pops up, then wait for the action to be processed.
* Restart Steemer

---

* App version: Steemer V 1.4.5
* Operating system: Android version 8. 1.0 Oreo Tecno camon Xpro. 

#### Recording Of The Bug
https://youtu.be/phyyo7_uGzE

**Comment by hispeedimagins** [comment]
Hello, Is it working now? If it still does not, you can change the nonce value in settings, that will speed the signing process.
