### ISSUE TITLE
The app will crash when uploading images when created a new post

### ISSUE THREAD

**Issue by shaphir** [hispeedimagins/steem#7]
#### Expected behavior
Allows me to upload images

#### Actual behavior
The application will crash when I uploading the image from the media

#### How to reproduce
* Open the app
* Go to creat the post
* upload the image in ```your post```
* After taking a picture from the media and uploading it, the app will only show a blank page and then will crashes

* App version: 1.4.4
* Operating system: Android 6.0.1

#### Recording Of The Bug
https://youtu.be/yKmDzm8nrkk

**Comment by mcyusuf** [comment]
Hello, this works quite well on my device. After selecting the picture, the app starts uploading, and the link inserted.
![20180715_053237](https://user-images.githubusercontent.com/35164646/42730620-e0b43cee-87f0-11e8-9001-d2d48cf89daa.gif)
```
Tested on Android 8.1 Oreo
App version 1.4.4
```

**Comment by shaphir** [comment]
exactly as I said, try on the device as I'm reporting. ```Androd 6.0.1```

**Comment by djavalord** [comment]
It it crashed in my own device. Not working for me.  Android 8.1.0 Oreo Tecno camon X

**Comment by mcyusuf** [comment]
Am using camon x also.

**Comment by hispeedimagins** [comment]
mmm, please try it now after updating the app, maybe this rogue and this bug which I cannot reproduce is fixed,
