### ISSUE TITLE
Upvote feature is not working

### ISSUE THREAD

**Issue by shaphir** [hispeedimagins/steem#8]
#### Actual behavior
When I do an upvote on a post, it only displays the old loading, while the upvote does not occur.

#### How to reproduce
* Open the app
* Go to feed
* Give the upvote on a one of the posts in the feed
* it's will only display loading long enough, while upvote will not happen

* App version: 1.4.4
* Operating system: Android 6.0.1

#### Recording of the bug
https://youtu.be/nmhwTQZfRLI

**Comment by mcyusuf** [comment]
Hi, the upvote perfectly works fine. It must be your internet connection problem. 
![20180715_050033](https://user-images.githubusercontent.com/35164646/42730445-21ba3c5c-87ec-11e8-865d-7a817917e387.gif)

**Comment by djavalord** [comment]
Upvote didn't work on my Android 8.1.0 and my network is very good

**Comment by hispeedimagins** [comment]
Ok, I never said it is a bug,
but since you have encountered it I am looking into it and have released an update. 
Please tell me if it gives out a toast which says signed after the processing one. This could be a signing issue not sure, have made changes, do tell me.
