### ISSUE TITLE
The app will crash when deleting some the draft

### ISSUE THREAD

**Issue by shaphir** [hispeedimagins/steem#9]
#### Expected behavior
Allows users to delete all drafts if they wish

#### Actual behavior
The app will crash when trying to deleted some drafts that have been in saved before.

Note:
> before, saved some the drafts before you reproduce this issue.

#### How to reproduce
* Open the app
* Go to draft
* Then, try deleting all the draft have your saved.
* I found the issue when deleting the last draft (4th draft), it's because I only saved 4 drafts before.

* App version: 1.4.4
* Operating system: Android 6.0.1

#### Recording Of The Bug
https://youtu.be/hrZkZXY8SWE

**Comment by djavalord** [comment]
Could be android version issue. Work very fine in my 8.1.0 Oreo

**Comment by shaphir** [comment]
@djavalord can you try it also on android 6.0.1? (if you have it)

**Comment by djavalord** [comment]
Sorry I don't have 6.01

**Comment by hispeedimagins** [comment]
To be clear I on 6.0 to 7.1 on emulators and phones. It could be a rogue bug, please update and tell me if it still happens.
